### ISSUE TITLE
08_pipeline_jobs

### ISSUE THREAD

**Issue by joek** [starkandwayne/concourse-tutorial#14]
For some reason the "job-run-task" is not triggered automated. I am a bit confused. Is this behaviour expected? I was expecting after running "job-fetch-resource" the second task will start but nothing is happen...

**Comment by drnic** [comment]
I'm not sure what the expected behavior of concourse is for new jobs.




When I started writing the tutorials I had wrapper script that also curl'd the API to trigger the build to start.




If you find a way to get new jobs to auto-run please let me know and then the tutorial can be updated to be a bit more awesome
