### ISSUE TITLE
Do you have a tutorial job to create a service on cf

### ISSUE THREAD

**Issue by rjain-pivotal** [starkandwayne/concourse-tutorial#42]
Currently, the cf resource is only used to put the app (deploy)

How do I create a service and bind it to an app and then tear it down after testing ?

**Comment by drnic** [comment]
Perhaps write a custom task to do these steps; rather than the cf resource which is for zero downtime deploy of an existing app I think?






On Mon, Apr 25, 2016 at 7:46 PM -0700, "Rajesh Jain" <notifications@github.com> wrote:












Currently, the cf resource is only used to put the app (deploy)



How do I create a service and bind it to an app and then tear it down after testing ?

**Comment by mkb** [comment]
I see a couple parts to this:

1. How do we perform those operations in Concourse?
2. How do we make sure Concourse performs the teardown even if the job fails?

The answer to Q1 is to put those actions into a shell script. If you can do it from the command line then Concourse can do the same thing as part of a task.

For Q2 we have `on_failure`. Just add an `on_failure` clause to your build plan and you can ensure cleanup is done even when your job fails. Details at: https://concourse.ci/on-failure-step.html

Does that answer your question, @rjain-pivotal?

For questions about Concourse in general (rather than this tutorial), you can also join the [Concourse Slack team](http://slack.concourse.ci/). Folks in there are always helpful when I have questions.

**Comment by mkb** [comment]
Actually, `ensure` is better for this case: https://concourse.ci/ensure-step.html
