### ISSUE TITLE
Memory being eaten up

### ISSUE THREAD

**Issue by xlr-8** [starkandwayne/concourse-tutorial#46]
Hello,

Thanks for this awesome tutorial, really like it!

I'm currently thinking about using concourse as a tool for our company, but for some reason the vagrant machine eats up all my memory when running the tasks about [Publishing Output](https://github.com/starkandwayne/concourse-tutorial#12---publishing-outputs). I doubt this is the expected behaviour.

I think the version of my softs are pretty up-to-date:

``` bash
# Linux kernel
> uname -a
Linux dragonfly 4.5.5-1-MANJARO #1 SMP PREEMPT Thu May 19 17:20:19 UTC 2016 x86_64 GNU/Linux

# Go, Vagrant & Chromium
> go version
go version go1.6.2 linux/amd64
> vagrant version
Installed Version: 1.8.1
Latest Version: 1.8.1

# Regarding the latest commit I have & version
> git show | head -n1
commit 39fee8cd012b36b6bcc0fa826894186d2d36a17a
> cat VERSION
1.2.0
> chromium --version
Chromium 51.0.2704.63 
```

If you have already faced this issue, or know where this is coming from it would be appreciated :)
Didn't see anything matching memory problem on the repository's past issues.

It might eventually be similar to: https://github.com/concourse/concourse/issues/334
I think that if it's a known issue in the tutorial, it might be good to warn the users about it.

Cheers!

**Comment by drnic** [comment]
Thanks for the nice words on the tutorial.
Sorry I can't think of any tips for vagrant/concourse - I suggest joining the Concourse slack channel and asking @vito or others there. They are wonderfully helpful.






On Tue, May 31, 2016 at 9:02 AM -0700, "xlr-8" <notifications@github.com> wrote:












Hello,



Thanks for this awesome tutorial, really like it!



I'm currently thinking about using concourse as a tool for our company, but for some reason the vagrant machine eats up all my memory when running the tasks about Publishing Output. I doubt this is the expected behaviour.



I think the version of my softs are pretty up-to-date:

# Linux kernel
> uname -a
Linux dragonfly 4.5.5-1-MANJARO #1 SMP PREEMPT Thu May 19 17:20:19 UTC 2016 x86_64 GNU/Linux

# Go & Vagrant
> go version
go version go1.6.2 linux/amd64
> vagrant version
Installed Version: 1.8.1
Latest Version: 1.8.1

# Regarding the latest commit I have & version
> git show | head -n1
commit 39fee8cd012b36b6bcc0fa826894186d2d36a17a
> cat VERSION
1.2.0



If you have already faced this issue, or know where this is coming from it would be appreciated :)

Didn't see anything matching memory problem on the repository's past issues.



Cheers!

**Comment by joshuajabbour** [comment]
I believe I've seen this too, as I've had to force restart my Mac three times in the last two hours. Though I don't think it's necessarily related to this tutorial; it happened for me the first time when I was just playing around with the Concourse docs.

**Comment by joshuajabbour** [comment]
Yes, definitely a memory issue. I just tested this, by first running `vagrant reload` and then building step 10. Activity Monitor reported `VBoxHeadless` going from 2.35GB memory to 4.75, and never dropping back down. (Obviously this could be a Vagrant issue, and I don't use vagrant for anything else right now, so it's hard to test more.)

**Comment by mkb** [comment]
I've not seen this issue in quite some time. @xlr-8 , @joshuajabbour have you seen this with Concourse 2.2.1 or later?

**Comment by xlr-8** [comment]
I haven't tested it with vagrant for some time, on docker I didn't have issues. Depending on @joshuajabbour feedback, I guess we could close it until someone else mention it.

**Comment by joshuajabbour** [comment]
I'd say close it, as I don't use concourse in vagrant so can't test it.
