### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by svenvarkel** [starkandwayne/concourse-tutorial#50]
Hi!

I started implementing Concourse but I've hit a big problem - memory is leaked and it kills the machine that it's running on. It seems that memory is leaked by the Docker containers that are re-built every time a build plan is executed or something.

I'm using OSX. 

Anybody else facing this problem?

**Comment by overdrive3000** [comment]
Hi @svenvarkel. I think there is a related issue at https://github.com/starkandwayne/concourse-tutorial/issues/46

**Comment by mkb** [comment]
Hi @svenvarkel, thanks for commenting.

I encountered similar problems with previous versions of Concourse but the Concourse team has addressed them in recent months. If you're still having an issue please chime in on issue #46. I'm closing this one since it looks like a duplicate.

If you think it's a separate issue and still going on, please speak up. Thanks!
